# fly.toml app configuration file generated for scramoney-delicate-leaf-2641 on 2024-01-28T17:41:15+09:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'scramoney'
primary_region = 'nrt'
console_command = '/rails/bin/rails console'

[build]

[[vm]]
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024

[[statics]]
  guest_path = '/rails/public'
  url_prefix = '/'
