# fly.toml app configuration file generated for scramoney on 2024-01-29T14:03:27+09:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'scramoney'
primary_region = 'nrt'
console_command = '/rails/bin/rails console'

[build]

[deploy]
  release_command = './bin/rails db:prepare'

[processes]
  app = './bin/rails server'
  sidekiq = 'bundle exec sidekiq'
  web = "bin/rails server"
  cron = "supercronic crontab"

[http_service]
  internal_port = 3000
  external_port = 443
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['web']

[[vm]]
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024

[[statics]]
  guest_path = '/rails/public'
  url_prefix = '/'

[[services]]
  processes = ["web"]

[[services.ports]]
  handlers = ["http"]
  port = 8080
  force_https = true